myshop/cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
]

myshop/coupons/urls.py
from django.urls import path
from .views import coupon_apply


urlpatterns = [
    path('apply/', coupon_apply, name='apply')
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('coupons/', include(('coupons.urls', 'coupons'), namespace='coupons')),
    path('', include(('shop.urls', 'shop'), namespace='shop'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('create/', views.order_create, name='order_create')
]

myshop/shop/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail')
]

myshop/cart/models.py
from django.db import models

myshop/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .cart import Cart
from .forms import CartAddProductForm
from shop.models import Product
from coupons.forms import CouponApplyForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    coupon_apply_form = CouponApplyForm()
    return render(request, 'cart/detail.html',
                  {'cart': cart,
                            'coupon_apply_form': coupon_apply_form})

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
<div class="cart-main" style="width: 100%">
    <h1>Your shopping cart</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Image       </th>
            <th scope="col">Product     </th>
            <th scope="col">Quantity    </th>
            <th scope="col">Remove      </th>
            <th scope="col">Unit price  </th>
            <th scope="col">Price       </th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img class="item-img-cart" src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'img/no_image.png' %}
                                {% endif %}" style="max-width: 75px; max-height: 75px;">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart:cart_remove' product.id %}">Remove</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}

        {% if cart.coupon %}
            <tr class="subtotal">
                <td>Subtotal</td>
                <td colspan="4"></td>
                <td class="num"><h4>$   {{ cart.get_total_price }}</h4></td>
            </tr>
            <tr>
                <td>
                    "{{ cart.coupon.code }}" coupon
                    ({{ cart.coupon.discount }}% off)
                </td>
                <td colspan="4"></td>
                <td class="num neg">
                    - ${{ cart.get_discount|floatformat:"2" }}
                </td>
            </tr>
        {% endif %}

        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">
                <h4>${{ cart.get_total_price_after_discount|floatformat:"2" }}</h4>
            </td>
        </tr>
        </tbody>
    </table>

    <form action="{% url 'coupons:apply' %}" method="post" style="margin-top: 10px;">
        {{ coupon_apply_form }}
            <input class="btn btn-outline-dark mt-auto" type="submit" value="Apply">
        {% csrf_token %}
    </form>

    <p class="text-right" style="margin-top: 10px;">
        <a href="{% url 'shop:product_list' %}" class="btn btn-outline-dark mt-auto">Continue shopping</a>
        <a href="{% url 'orders:order_create' %}" class="btn btn-outline-dark mt-auto">
            Checkout
        </a>
    </p>
</div>
{% endblock %}